dependencies:
- alias: expose
  name: exposecontroller
  repository: https://aliacs-app-catalog.oss-cn-hangzhou.aliyuncs.com/charts-incubator/
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: https://aliacs-app-catalog.oss-cn-hangzhou.aliyuncs.com/charts-incubator/
  version: 2.3.82
- name: jenkins-x-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
